package webserver_test

import (
	"fmt"
	"net/http"
	"io/ioutil"
)

func ExampleHttpGet() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	resp, err := http.Get("http://localhost:8080")
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	fmt.Println(string(body))
	// Output: Hello Go!
}