package main

import (
	"fmt"
	//"io/ioutil"
	"net/http"
	//	"net/http/httptest"
	"testing"
)

func TestHandlerSlack(t *testing.T) {
	resp, err := http.NewRequest("GET", "/slack", nil)
	if err != nil {
		t.Fatal("Root request error: %s", err)
	}
	//defer resp.Body.Close()
	//body, err := ioutil.ReadAll(resp.Body)
	fmt.Println((resp.Body))

}

/*
func ExampleHttpGet() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	resp, err := http.Get("http://localhost:8080")
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	fmt.Println(string(body))
	// Output: Hello Go!
}
*/
